### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by Kranzes** [gibbz00/rops#18]
Why is the Cargo.lock in the gitignore? Do you want your project to be on purpose hard to debug and reproduce?

**Comment by gibbz00** [comment]
No, I had it from the beginning when prototyping to reduce git diffs and forgot to put it back. Thanks for pointing it out! I'll make sure to fix this tomorrow.

**Comment by Kranzes** [comment]
Okay thank god, I was worried I was gonna have to convince another person why lock files and reproducible builds are important.

**Comment by gibbz00** [comment]
Hehe nah, we're on the same page there :) Fixed in https://github.com/gibbz00/rops/commit/e081458e511b738aaed9b9983fe57dfef6743dfc
